<a href="https://colab.research.google.com/github/san031/Machine_learning-Artificial-Intelligence-Projects/blob/main/machine_learning/linear_regression/BengaluruHousePredictionFinal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv("/content/sample_data/Bengaluru_House_Data.csv")

In [ ]:
df.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [ ]:
df.shape

(13320, 9)

In [ ]:
df.describe()

               bath       balcony         price
count  13247.000000  12711.000000  13320.000000
mean       2.692610      1.584376    112.565627
std        1.341458      0.817263    148.971674
min        1.000000      0.000000      8.000000
25%        2.000000      1.000000     50.000000
50%        2.000000      2.000000     72.000000
75%        3.000000      2.000000    120.000000
max       40.000000      3.000000   3600.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

In [ ]:
df['area_type'].value_counts()

area_type
Super built-up  Area    8790
Built-up  Area          2418
Plot  Area              2025
Carpet  Area              87
Name: count, dtype: int64

In [ ]:
df['location'].value_counts()

location
Whitefield                         540
Sarjapur  Road                     399
Electronic City                    302
Kanakpura Road                     273
Thanisandra                        234
                                  ...
3rd Stage Raja Rajeshwari Nagar      1
Chuchangatta Colony                  1
Electronic City Phase 1,             1
Chikbasavanapura                     1
Abshot Layout                        1
Name: count, Length: 1305, dtype: int64

In [ ]:
df.isnull().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

### Data Cleaning

In [ ]:
df = df.drop(['area_type', 'society','balcony','availability'], axis = 1)

In [ ]:
df.columns

Index(['location', 'size', 'total_sqft', 'bath', 'price'], dtype='object')

In [ ]:
df.columns

Index(['location', 'size', 'total_sqft', 'bath', 'price'], dtype='object')

In [ ]:
df.head()

                   location       size total_sqft  bath   price
0  Electronic City Phase II      2 BHK       1056   2.0   39.07
1          Chikka Tirupathi  4 Bedroom       2600   5.0  120.00
2               Uttarahalli      3 BHK       1440   2.0   62.00
3        Lingadheeranahalli      3 BHK       1521   3.0   95.00
4                  Kothanur      2 BHK       1200   2.0   51.00

In [ ]:
df.isnull().sum()

location       1
size          16
total_sqft     0
bath          73
price          0
dtype: int64

In [ ]:
##### removing missing values

In [ ]:
df = df.dropna()

In [ ]:
df.isnull().sum()

location      0
size          0
total_sqft    0
bath          0
price         0
dtype: int64

### converting size to bhk

In [ ]:
df['bhk'] = df['size'].apply(lambda x: x.split(' ')[0])

In [ ]:
df.head

<bound method NDFrame.head of                  location  total_sqft  bath    price bhk
30              Yelahanka      2475.0   4.0  186.000   4
122                Hebbal      5611.5   4.0  477.000   4
137    8th Phase JP Nagar      1073.5   2.0   54.005   2
165              Sarjapur      1242.5   2.0   43.490   2
188              KR Puram      1277.5   2.0   56.800   2
...                   ...         ...   ...      ...  ..
12975          Whitefield       955.0   2.0   38.190   2
12990      Talaghattapura      2038.5   3.0  122.000   3
13059              Harlur      1335.0   2.0   72.760   2
13265               Hoodi      1258.5   2.0   59.135   2
13299          Whitefield      2856.0   5.0  154.500   4

[144 rows x 5 columns]>

In [ ]:
df['total_sqft'].value_counts()

total_sqft
1200     843
1100     221
1500     204
2400     195
600      180
        ...
2383       1
4830       1
555        1
785        1
804.1      1
Name: count, Length: 2067, dtype: int64

In [ ]:
df['total_sqft'].unique()

array(['1056', '2600', '1440', ..., '1133 - 1384', '774', '4689'],
      dtype=object)

In [ ]:
def convert_sqft_to_num(x):
  token = x.split('-')
  if len(token) == 2:
    return(float(token[0]) +  float(token[1]))/2

In [ ]:
df['total_sqft'] = df['total_sqft'].apply(convert_sqft_to_num)

In [ ]:
df['total_sqft'].unique()

array([     nan, 2475.   , 5611.5  , 1073.5  , 1242.5  , 1277.5  ,
       1317.5  , 1132.5  , 4046.   , 1177.5  , 1122.5  ,  582.5  ,
       1142.5  ,  657.5  ,  649.5  , 1450.   , 1000.   ,  971.5  ,
        687.325,  615.   , 3430.   , 2038.5  , 3715.   , 4624.5  ,
        825.   , 1128.76 , 1104.   ,  790.5  , 3035.   , 2856.   ,
        700.   , 1559.   , 1352.5  , 1185.5  , 1005.   , 3181.   ,
       1192.5  , 2912.5  ,  630.5  ,  717.   , 1343.5  , 3416.5  ,
       1312.5  , 1137.5  ,  458.   ,  709.   ,  605.   , 2987.5  ,
       1089.   ,  680.   ,  412.5  ,  805.5  , 1617.5  , 1302.5  ,
        975.   , 2585.5  , 2648.   ,  614.5  , 2336.5  , 3317.5  ,
       1405.   , 1532.5  , 1115.   , 1580.   , 1272.5  ,  925.   ,
        698.5  , 1431.5  , 1029.5  ,  778.   , 1155.   , 1700.   ,
        784.   , 3385.5  ,  777.   , 2464.5  ,  640.   , 3854.5  ,
       4920.   ,  762.5  ,  693.   ,  728.5  ,  800.   ,  552.5  ,
        775.   , 1732.5  , 1131.   , 2835.   , 1260.   , 1081.5  ,
       2065.5  ,  583.   , 1237.5  ,  711.   ,  801.   , 2630.   ,
        863.   , 5020.   , 1315.   ,  612.5  ,  907.   , 2820.   ,
       1360.   ,  720.   , 1172.   ,  747.   , 1590.   , 1570.   ,
       1322.5  , 1003.5  , 2187.5  , 1639.5  ,  827.5  , 1355.   ,
       1195.   , 2500.   , 1187.   , 5667.5  , 1830.5  , 2858.   ,
        705.   , 1410.5  , 4225.   , 1533.   ,  955.   , 1335.   ,
       1258.5  ])

##remove invalid sqft rows

In [ ]:
df = df[df['total_sqft'].notnull()]

## create a price per sqft

In [ ]:
df['price_per_sqft'] = (df['price']*10000)/df['total_sqft']

/tmp/ipykernel_2138/3565887607.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['price_per_sqft'] = (df['price']*10000)/df['total_sqft']

In [ ]:
df.head()

               location   size  total_sqft  bath    price bhk  price_per_sqft
30            Yelahanka  4 BHK      2475.0   4.0  186.000   4      751.515152
122              Hebbal  4 BHK      5611.5   4.0  477.000   4      850.040096
137  8th Phase JP Nagar  2 BHK      1073.5   2.0   54.005   2      503.074057
165            Sarjapur  2 BHK      1242.5   2.0   43.490   2      350.020121
188            KR Puram  2 BHK      1277.5   2.0   56.800   2      444.618395

In [ ]:
df = df.drop(['price_per_sqft'], axis = 1)

### remove extra spaces in location

In [ ]:
df['location'] = df['location'].apply(lambda x:x.strip())

In [ ]:
df.head()

               location   size  total_sqft  bath    price bhk
30            Yelahanka  4 BHK      2475.0   4.0  186.000   4
122              Hebbal  4 BHK      5611.5   4.0  477.000   4
137  8th Phase JP Nagar  2 BHK      1073.5   2.0   54.005   2
165            Sarjapur  2 BHK      1242.5   2.0   43.490   2
188            KR Puram  2 BHK      1277.5   2.0   56.800   2

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 144 entries, 30 to 13299
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    144 non-null    object
 1   size        144 non-null    object
 2   total_sqft  144 non-null    float64
 3   bath        144 non-null    float64
 4   price       144 non-null    float64
 5   bhk         144 non-null    object
dtypes: float64(3), object(3)
memory usage: 7.9+ KB

### Encoding :  convert string or object datatype to integer

#### one hot encoding

In [ ]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [ ]:
df = df.drop(['size'], axis = 1)

In [ ]:
df

                 location  total_sqft  bath    price bhk
30              Yelahanka      2475.0   4.0  186.000   4
122                Hebbal      5611.5   4.0  477.000   4
137    8th Phase JP Nagar      1073.5   2.0   54.005   2
165              Sarjapur      1242.5   2.0   43.490   2
188              KR Puram      1277.5   2.0   56.800   2
...                   ...         ...   ...      ...  ..
12975          Whitefield       955.0   2.0   38.190   2
12990      Talaghattapura      2038.5   3.0  122.000   3
13059              Harlur      1335.0   2.0   72.760   2
13265               Hoodi      1258.5   2.0   59.135   2
13299          Whitefield      2856.0   5.0  154.500   4

[144 rows x 5 columns]

In [ ]:
X = df.drop(['price'], axis = 1)
y = df['price']

ohe = OneHotEncoder(handle_unknown="ignore",sparse_output = True)

In [ ]:
ohe

OneHotEncoder(handle_unknown='ignore')

#### creating a column transformer

In [ ]:
categorical_features = ['location']

In [ ]:
preprocessor = ColumnTransformer(
    transformers = [
        ('location_encoder', ohe, categorical_features)
    ],
    remainder = 'passthrough'
)

#### splitting the data

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train,y_test =train_test_split(X, y,test_size = 0.2,random_state = 42)

### Fit and Transform

In [ ]:
df.head()

               location  total_sqft  bath    price bhk
30            Yelahanka      2475.0   4.0  186.000   4
122              Hebbal      5611.5   4.0  477.000   4
137  8th Phase JP Nagar      1073.5   2.0   54.005   2
165            Sarjapur      1242.5   2.0   43.490   2
188            KR Puram      1277.5   2.0   56.800   2

In [ ]:
X_train_emcoded = preprocessor.fit_transform(X_train)

In [ ]:
X_test_emcoded = preprocessor.transform(X_test)

In [ ]:
X_train_emcoded.shape

(115, 54)

In [ ]:
X_test_emcoded.shape

(29, 54)

### get feature names

In [ ]:
feature_names = preprocessor.get_feature_names_out()

In [ ]:
feature_names

array(['location_encoder__location_8th Phase JP Nagar',
       'location_encoder__location_Anwar Layout',
       'location_encoder__location_Balagere',
       'location_encoder__location_Banashankari Stage VI',
       'location_encoder__location_Bannerghatta Road',
       'location_encoder__location_Begur Road',
       'location_encoder__location_Bettahalsoor',
       'location_encoder__location_Budigere',
       'location_encoder__location_Carmelaram',
       'location_encoder__location_Chandapura',
       'location_encoder__location_Devanahalli',
       'location_encoder__location_EPIP Zone',
       'location_encoder__location_Electronic City Phase II',
       'location_encoder__location_Electronics City Phase 1',
       'location_encoder__location_Harlur',
       'location_encoder__location_Hebbal',
       'location_encoder__location_Hennur Road',
       'location_encoder__location_Hoodi',
       'location_encoder__location_Hormavu',
       'location_encoder__location_Hosa Road',
       'location_encoder__location_Hoskote',
       'location_encoder__location_Hosur Road',
       'location_encoder__location_Hulimavu',
       'location_encoder__location_ITPL',
       'location_encoder__location_Iblur Village',
       'location_encoder__location_JP Nagar',
       'location_encoder__location_Jakkur',
       'location_encoder__location_Jalahalli',
       'location_encoder__location_Jalahalli East',
       'location_encoder__location_KR Puram',
       'location_encoder__location_Kadugodi',
       'location_encoder__location_Kanakapura',
       'location_encoder__location_Kanakpura Road',
       'location_encoder__location_Magadi Road',
       'location_encoder__location_Mysore Road',
       'location_encoder__location_Old Madras Road',
       'location_encoder__location_Omarbagh Layout',
       'location_encoder__location_Pragathi Nagar',
       'location_encoder__location_Rachenahalli',
       'location_encoder__location_Rajaji Nagar',
       'location_encoder__location_Sarjapur',
       'location_encoder__location_Sarjapur  Road',
       'location_encoder__location_Sonnenahalli',
       'location_encoder__location_Talaghattapura',
       'location_encoder__location_Thanisandra',
       'location_encoder__location_Tumkur Road',
       'location_encoder__location_Uttarahalli',
       'location_encoder__location_Varthur Road',
       'location_encoder__location_Whitefield',
       'location_encoder__location_Yelahanka',
       'location_encoder__location_Yeshwanthpur', 'remainder__total_sqft',
       'remainder__bath', 'remainder__bhk'], dtype=object)

### training the model

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
lr = LinearRegression()

In [ ]:
lr.fit(X_train_emcoded,y_train)

LinearRegression()

In [ ]:
y_pred = lr.predict(X_test_emcoded)

#### Accuracy

In [ ]:
from sklearn.metrics import r2_score

In [ ]:
accuracy = r2_score(y_test, y_pred)

In [ ]:
accuracy

0.8679442073765331